image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - deploy

before_script:
  - npm install -g firebase-tools
  - npm --prefix ./firebase/functions install

deploy_staging:
  stage: deploy
  environment: staging
  script:
    - npm --prefix ./firebase/functions run deploy
  only:
    - master
