image: node:latest

cache:
  paths:
    - node_modules/
    - app/bower_components

deploy_production:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - npm install -g firebase-tools
    - cd firebase/functions
    - npm i
    - cd ..
    - firebase use property --token $FIREBASE_DEPLOY_KEY
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
